"""Mesh-health guards for the ready-to-print STL library shipped under ``stl/``.

The library is generated by ``scripts/build_release_stls.py`` (9 plug tools +
16 measuring-stencil cards, laid out as ``stl/Plug-Puller/`` and
``stl/Measuring-Stencil/{Visual,Tactile}/``). This test reuses that script's
job catalog as the single source of truth, so the guards can never drift from
what actually ships.

Quick lane (no OpenSCAD):

* Every shipped STL exists, is watertight, and has consistent winding — the
  historical failure class here was non-watertight minkowski output (v5-era),
  so this pins the fix permanently across the whole library.

Render lane (``@requires_openscad``):

* Every shipped STL still re-renders mesh-equivalent to its source SCAD +
  parameters, so the committed downloads can never silently drift from the
  validated model. When an intentional model change trips this, re-run
  ``python scripts/build_release_stls.py`` and commit the refreshed ``stl/``.

License: PolyForm Noncommercial 1.0.0
"""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts.build_release_stls import Job, plug_jobs, stencil_jobs

PROJECT_ROOT = Path(__file__).resolve().parent.parent
STL_DIR = PROJECT_ROOT / "stl"

SHIPPED_JOBS = plug_jobs() + stencil_jobs()
SHIPPED_IDS = [job.out_rel.as_posix() for job in SHIPPED_JOBS]


def _shipped_path(job: Job) -> Path:
    return STL_DIR / job.out_rel


@pytest.mark.parametrize("job", SHIPPED_JOBS, ids=SHIPPED_IDS)
def test_shipped_stl_watertight(job: Job) -> None:
    import trimesh

    path = _shipped_path(job)
    assert path.exists(), (
        f"Shipped STL missing: {path}\n"
        f"Regenerate the library with: python scripts/build_release_stls.py"
    )

    mesh = trimesh.load(path, force="mesh")
    assert isinstance(mesh, trimesh.Trimesh), f"{job.out_rel} did not load as a mesh"
    assert mesh.is_watertight, (
        f"{job.out_rel} is not watertight — slicers may reject or mis-slice it. "
        f"Re-render it from the source SCAD and investigate the geometry."
    )
    assert mesh.is_winding_consistent, (
        f"{job.out_rel} has inconsistent face winding (flipped normals)."
    )


@pytest.mark.requires_openscad
@pytest.mark.slow
@pytest.mark.parametrize("job", SHIPPED_JOBS, ids=SHIPPED_IDS)
def test_shipped_stl_matches_source(
    job: Job, openscad_runner, mesh_comparator, tmp_path: Path
) -> None:
    shipped = _shipped_path(job)
    assert shipped.exists(), (
        f"Shipped STL missing: {shipped}\n"
        f"Regenerate the library with: python scripts/build_release_stls.py"
    )
    assert job.scad.exists(), f"Source SCAD missing: {job.scad}"

    output = tmp_path / job.out_rel.name
    result = openscad_runner.generate_stl(
        scad_file=job.scad,
        output_stl=output,
        parameters=job.params,
    )
    assert result.success, (
        f"Render of {job.out_rel} failed "
        f"(returncode={result.returncode}):\n{result.stderr}"
    )
    assert output.stat().st_size > 0, f"Fresh render of {job.out_rel} is empty."

    import trimesh

    mesh = trimesh.load(output, force="mesh")
    assert mesh.is_watertight, f"Fresh render of {job.out_rel} is not watertight."

    comparison = mesh_comparator.compare(shipped, output)
    if not comparison.passed:
        details = "\n".join(f"  - {f}" for f in comparison.failures)
        pytest.fail(
            f"Shipped stl/{job.out_rel.as_posix()} has drifted from a fresh "
            f"render of its source ({job.scad.name}, params={job.params}):\n"
            f"{details}\n"
            f"If the model changed intentionally, re-render the library with "
            f"python scripts/build_release_stls.py and commit stl/."
        )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
