// =============================================================================
// generate_braille_labels.mjs — one-time Liblouis translation of the braille
// flap titles for Measuring_Stencil.scad (Tactile mode).
// =============================================================================
//
// Run manually (never in CI) whenever the label wording changes:
//
//     node scripts/generate_braille_labels.mjs
//
// It translates the LABELS strings below to UEB Grade 2 Unicode braille with
// the SAME engine + table chain the openscad-assistive-forge web UI uses
// (liblouis, unicode.dis + en-ueb-g2.ctb), then:
//
//   1. writes scripts/braille_labels.json  (committed — the drift-lock source
//      that tests/test_braille_labels.py checks the SCAD against), and
//   2. prints the SCAD-ready BRAILLE_LABELS constant to stdout for pasting
//      into Measuring_Stencil.scad.
//
// Rules mirrored from the forge (src/worker/liblouis-worker.js):
//   * input is lowercased (Grade 2 signage style, no capital indicators),
//   * table chain unicode.dis,en-ueb-g2.ctb (unicode.dis first forces
//     Unicode braille output),
//   * ASCII spaces in the output are replaced with U+2800 (braille blank) so
//     every codepoint of the stored string is in [U+2800, U+28FF].
//
// Requires a local clone of openscad-assistive-forge (the FORGE path below)
// with its node_modules installed and public/liblouis/tables populated.
//
// License: PolyForm Noncommercial 1.0.0

import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const FORGE = "C:/Users/WATAP/Documents/github/openscad-assistive-forge";

// Reuse the forge's installed liblouis build. In the Node build the table
// folder is mounted at /tables inside the emscripten FS, so chain entries
// need the tables/ prefix (the browser worker uses bare names instead).
const require = createRequire(join(FORGE, "package.json"));
const liblouis = require("liblouis");
liblouis.enableOnDemandTableLoading(resolve(join(FORGE, "public/liblouis/tables")));

const TABLE = "unicode.dis,en-ueb-g2.ctb";
const NODE_CHAIN = "tables/unicode.dis,tables/en-ueb-g2.ctb";

// One vector of flap lines per card, in Measuring_Stencil.scad card-index
// order (0-6 = P1, P2, P3, R1, C1, F1, F2). Wording is chosen so every
// translated line fits its card: cells * 7 mm + 2 * 4 mm flap margin must
// stay <= the Tactile-mode card width (see MAX_CELLS below).
const LABELS = {
  P1: ["lamp", "2 prong"],
  P2: ["standard", "3 prong"],
  P3: ["heavy duty", "cord"],
  R1: ["ruler 100 mm", "notches 10 mm"],
  C1: ["cord gauge mm"],
  F1: ["finger sizing 1 of 2", "width: hole minus 5"],
  F2: ["finger sizing 2 of 2", "width: hole minus 5"],
};

// Per-card cell budgets: floor((tactile_card_width - 2*FLAP_MARGIN) / 7).
// Duplicated from Measuring_Stencil.scad's card width functions —
// tests/test_braille_labels.py re-derives these independently.
const MAX_CELLS = { P1: 9, P2: 10, P3: 11, R1: 13, C1: 13, F1: 21, F2: 19 };

const BRAILLE_ONLY = /^[\u2800-\u28FF]+$/;

const out = {};
let failed = false;
for (const [card, lines] of Object.entries(LABELS)) {
  out[card] = lines.map((text) => {
    const braille = liblouis
      .translateString(NODE_CHAIN, text.toLowerCase())
      .replace(/ /g, "\u2800");
    if (!BRAILLE_ONLY.test(braille)) {
      console.error(`ERROR: ${card} "${text}" produced non-braille output: ${braille}`);
      failed = true;
    }
    const status = braille.length <= MAX_CELLS[card] ? "ok" : "TOO WIDE";
    if (status !== "ok") failed = true;
    console.error(
      `${card}  "${text}" -> ${braille}  (${braille.length}/${MAX_CELLS[card]} cells, ${status})`
    );
    return braille;
  });
}

const payload = {
  generator: "scripts/generate_braille_labels.mjs",
  table: TABLE,
  cards: Object.fromEntries(
    Object.entries(LABELS).map(([card, lines]) => [
      card,
      { source: lines, braille: out[card] },
    ])
  ),
};

const here = dirname(fileURLToPath(import.meta.url));
const jsonPath = join(here, "braille_labels.json");
writeFileSync(jsonPath, JSON.stringify(payload, null, 2) + "\n", "utf-8");
console.error(`\nWrote ${jsonPath}`);

// SCAD-ready constant on stdout.
const order = ["P1", "P2", "P3", "R1", "C1", "F1", "F2"];
console.log("// Grade 2 UEB, generated by scripts/generate_braille_labels.mjs — do not hand-edit.");
for (const card of order) {
  console.log(`// ${card}: ${LABELS[card].map((s) => JSON.stringify(s)).join(", ")}`);
}
console.log("BRAILLE_LABELS = [");
order.forEach((card, i) => {
  const lines = out[card].map((s) => `"${s}"`).join(", ");
  console.log(`    [${lines}]${i < order.length - 1 ? "," : ""}  // ${card}`);
});
console.log("];");

if (failed) {
  console.error("\nFAILED: fix the wording above and re-run.");
  process.exit(1);
}
